# Generated by Django 4.0.5 on 2022-10-25 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church', '0002_membershipregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_type', models.CharField(choices=[('church', 'Church'), ('group', 'Group')], max_length=20)),
                ('title', models.CharField(max_length=225)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purse', models.DecimalField(decimal_places=2, default='00.00', max_digits=20)),
                ('fund', models.DecimalField(decimal_places=2, default='00.00', max_digits=20)),
                ('chalenges', models.TextField()),
                ('date_created', models.DateTimeField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('attendance', models.IntegerField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.program')),
                ('unit_dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church.unitsanddepartments')),
            ],
        ),
    ]
