# Generated by Django 3.2.25 on 2024-09-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_upcomingevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upcomingevent',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='upcomingevent',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
