# Generated by Django 4.0.5 on 2022-10-27 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_counciloffice_councilmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='unit_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.unitsanddepartments'),
        ),
    ]
