# Generated by Django 4.0.5 on 2022-11-02 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_alter_attendance_unit_dept'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipregister',
            name='unit_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='church.unitsanddepartments'),
        ),
    ]
