# Generated by Django 4.0.5 on 2022-11-02 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('church', '0006_membershipregister_unit_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipregister',
            name='unit_dept',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='unit_dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.unitsanddepartments'),
        ),
        migrations.DeleteModel(
            name='CouncilMember',
        ),
        migrations.DeleteModel(
            name='CouncilOffice',
        ),
        migrations.DeleteModel(
            name='MembershipRegister',
        ),
        migrations.DeleteModel(
            name='UnitsAndDepartments',
        ),
    ]
