# Generated by Django 4.0.5 on 2022-11-13 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0008_activities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activities',
        ),
    ]
