# Generated by Django 4.0.5 on 2022-11-13 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0009_delete_activities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('days', models.CharField(max_length=15)),
                ('time', models.TimeField()),
            ],
        ),
    ]
