# Generated by Django 4.0.5 on 2022-11-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0010_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activities',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
