# Generated by Django 4.0.5 on 2022-11-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0011_alter_activities_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='comment',
            field=models.CharField(default='ok', max_length=225),
            preserve_default=False,
        ),
    ]
