# Generated by Django 4.0.5 on 2022-11-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0013_attendance_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='comment',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
