# Generated by Django 4.0.5 on 2022-11-20 15:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church', '0015_requestfund_requestapproval'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestApproval',
            new_name='ApproveFundRequest',
        ),
        migrations.RenameModel(
            old_name='RequestFund',
            new_name='FundRequest',
        ),
    ]
