# Generated by Django 4.0.5 on 2022-11-20 15:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church', '0016_rename_requestapproval_approvefundrequest_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApproveFundRequest',
            new_name='FundRequestApproval',
        ),
    ]
