# Generated by Django 4.0.5 on 2022-11-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0017_rename_approvefundrequest_fundrequestapproval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundrequest',
            name='request_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
