# Generated by Django 4.2.4 on 2024-02-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0018_alter_fundrequest_request_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundrequest',
            old_name='approval',
            new_name='approved',
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
