# Generated by Django 4.2.4 on 2024-03-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0019_rename_approval_fundrequest_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
