# Generated by Django 4.2.4 on 2024-03-05 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0020_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/gallery'),
        ),
    ]
