# Generated by Django 4.2.4 on 2024-03-05 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0021_alter_image_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageGallery',
        ),
    ]
