# Generated by Django 4.2.4 on 2024-03-05 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0022_rename_image_imagegallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='title',
        ),
    ]
