# Generated by Django 4.2.4 on 2024-03-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0024_imagecollection_imagegallery_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagegallery',
            name='image',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
