# Generated by Django 4.2.4 on 2024-03-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0025_alter_imagegallery_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='collection',
        ),
        migrations.DeleteModel(
            name='ImageCollection',
        ),
        migrations.DeleteModel(
            name='ImageGallery',
        ),
    ]
