# Generated by Django 4.0.5 on 2022-11-02 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipregister',
            name='email',
        ),
        migrations.RemoveField(
            model_name='membershipregister',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='membershipregister',
            name='lastname',
        ),
        migrations.AddField(
            model_name='membershipregister',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membershipregister',
            name='othernames',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
