# Generated by Django 3.2.25 on 2024-09-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_councilmember_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitsanddepartments',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
