# Generated by Django 4.2.4 on 2024-03-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_membershipregister_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitsanddepartments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/group_images'),
        ),
    ]
