# Generated by Django 4.2.4 on 2024-03-07 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_unitsanddepartments_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitsanddepartments',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_images'),
        ),
    ]
