# Generated by Django 4.2.4 on 2024-03-08 15:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='audiolibrary',
            name='collection',
        ),
        migrations.RemoveField(
            model_name='audiolibrary',
            name='image',
        ),
        migrations.AddField(
            model_name='audiolibrary',
            name='_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiolibrary',
            name='audio',
            field=models.FileField(default=1, upload_to='audio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiolibrary',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='files.audiogenre'),
            preserve_default=False,
        ),
    ]
