# Generated by Django 4.2.4 on 2024-03-08 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_audiogenre_remove_audiolibrary_collection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audio')),
                ('description', models.CharField(max_length=255)),
                ('_date', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='AudioGenre',
            new_name='MediaCategory',
        ),
        migrations.DeleteModel(
            name='AudioLibrary',
        ),
        migrations.AddField(
            model_name='medialibrary',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.mediacategory'),
        ),
    ]
