# Generated by Django 4.2.4 on 2024-03-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_medialibrary_rename_audiogenre_mediacategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medialibrary',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
