# Generated by Django 4.2.4 on 2024-03-10 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_medialibrary_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medialibrary',
            old_name='_date',
            new_name='file_date',
        ),
    ]
